workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
       
  
        
      vars:
        PACKAGE_NAME: "com.app.crmapp"
   
